In [1]:
import torch
import numpy as np

In [25]:
print(torch.__version__)

1.6.0


In [26]:
torch.cuda.is_available()

True

In [27]:
torch.version.cuda

'10.2'

# Using CUDA

In [6]:
t = torch.tensor([1,2,3])
t

tensor([1, 2, 3])

In [7]:
t = t.cuda()
t

tensor([1, 2, 3], device='cuda:0')

# Checking out Tensors

In [9]:
a = np.random.randint(0, 9, (3,4))
a

array([[2, 2, 0, 3],
       [1, 5, 0, 1],
       [7, 4, 8, 0]])

In [11]:
t = torch.tensor(a)
print(t)
print(type(t))
print(t.shape)

tensor([[2, 2, 0, 3],
        [1, 5, 0, 1],
        [7, 4, 8, 0]], dtype=torch.int32)
<class 'torch.Tensor'>
torch.Size([3, 4])


#### Now try reshaping 3x4 array to 2x6

In [14]:
v = t.reshape(2,6)

In [15]:
v.shape

torch.Size([2, 6])

#### Examples of element-wise operations

#### Interactions between tensors of same rank and shape will interact in an element-wise way

In [2]:
t1 = torch.tensor([
    [1,2],
    [3,4]
], dtype = torch.float32)

t2 = torch.tensor([
    [9,8],
    [7,6]
], dtype = torch.float32)

In [3]:
t1 + t2

tensor([[10., 10.],
        [10., 10.]])

#### Tensors interacting with scalars will *boradcast* the scalar to a tensor of the same shape, then operate on it element-wise

In [4]:
t1 + 2

tensor([[3., 4.],
        [5., 6.]])

#### This is true for tensors of different sizes operating on each other too. 

In [13]:
t1 = torch.tensor([
    [1,1],
    [1,1]
], dtype = torch.float32)

t2 = torch.tensor([2,4], dtype = torch.float32)

print(t1.shape)
print(t2.shape)

print(t1 + t2)

print(np.broadcast_to(t2.numpy(), t1.shape))

print(t1 + np.broadcast_to(t2.numpy(), t1.shape))

torch.Size([2, 2])
torch.Size([2])
tensor([[3., 5.],
        [3., 5.]])
[[2. 4.]
 [2. 4.]]
tensor([[3., 5.],
        [3., 5.]])


#### Comparison opertations are also element-wise

In [14]:
t = torch.tensor([
    [0,5,7],
    [6,0,7],
    [0,8,0]
], dtype = torch.float32)

t.eq(0)

tensor([[ True, False, False],
        [False,  True, False],
        [ True, False,  True]])

In [15]:
t == torch.tensor([
    [0,0,0],
    [0,0,0],
    [0,0,0]
], dtype = torch.float32)

tensor([[ True, False, False],
        [False,  True, False],
        [ True, False,  True]])

#### Now to look at reduction operations - operations which reduce the number of elements in a tensor

In [16]:
t = torch.tensor([
    [0,1,0],
    [2,0,2],
    [0,3,0]
], dtype = torch.float32)

print(t.sum())
print(t.numel())
print(t.sum().numel())

tensor(8.)
9
1


In [17]:
t.sum(dim = 0)

tensor([2., 4., 2.])

In [18]:
t.sum(dim = 1)

tensor([1., 4., 3.])

In [19]:
t.argmax()

tensor(7)

In [20]:
t.flatten()

tensor([0., 1., 0., 2., 0., 2., 0., 3., 0.])

In [21]:
t.max(dim = 0)

torch.return_types.max(
values=tensor([2., 3., 2.]),
indices=tensor([1, 2, 1]))

In [22]:
t.max(dim = 1)

torch.return_types.max(
values=tensor([1., 2., 3.]),
indices=tensor([1, 0, 1]))

#### To access elements of sum, mean, etc, use item, which works on scalar tensors, or .tolist/.numpy

In [23]:
t.mean().item()

0.8888888955116272

In [24]:
t.mean(dim = 0).numpy()

array([0.6666667, 1.3333334, 0.6666667], dtype=float32)